<template>
  <section id="rarity" class="cards">
    <div class="container">
      <div class="info info--cards">
        <div class="info__pictures">
          <div v-for="(picture, i) in pictures" :key="i" class="info__picture">
            <img :src="picture.src" :alt="picture.alt" />
          </div>
        </div>
        <div class="info__texts-wrapper">
          <div class="info__texts">
            <div class="info__text">
              <h3>{{ texts[0].title }}</h3>
              <p v-for="(text, j) in texts[0].paragraphs" :key="j" v-html="text.text"></p>
              <template v-if="texts[0].paragraphs[1].categories">
                <ul class="info__list">
                  <li v-for="(category, i) in texts[0].paragraphs[1].categories" :key="i">
                    <span>{{ category.text }}</span>
                  </li>
                </ul>
              </template>
            </div>

            <div class="info__text">
              <h3>{{ texts[1].title }}</h3>
              <p v-for="(text, j) in texts[1].paragraphs" :key="j" v-html="text.text"></p>
            </div>
          </div>
        </div>
      </div>
      <div class="cards__divider"></div>
    </div>
  </section>
</template>

<script>
export default {
  name: 'Lottery',
  data() {
    return {
      texts: [
        {
          title: 'Cards’ Rarity',
          paragraphs: [
            {
              text: 'Each Card is generated by combining the text of prediction and the art. Of course, some Cards are rarer than others, and among them are very special ones, called <strong>Lucky Cards.</strong>'
            },
            {
              text: 'There will be the following 8 categories:',
              categories: [
                {
                  text: 'Love and relationships - 23%'
                },
                {
                  text: 'Job - 23%'
                },
                {
                  text: 'Signs - 15%'
                },
                {
                  text: 'Family - 15%'
                },
                {
                  text: 'MMXXI - 10%'
                },
                {
                  text: 'Success - 10%'
                },
                {
                  text: 'Investments  - 3%'
                },
                {
                  text: 'Crypto - 1%'
                }
              ]
            }
          ]
        },
        {
          title: '3 types of Lucky Cards:',
          paragraphs: [
            {
              text: '<strong>Ξ Cards</strong> and <strong>Treasure Chest Cards.</strong> Every O.R.A.C.L.E. holder has a chance to get this special card and receive a <strong>Joker Cards.</strong> !'
            },
            {
              text: 'These are super rare! It’s only 4 of them and each gives 1/4 of the O.R.A.C.L.E. OpenSea royalties to its lucky holder! 100% in total'
            }
          ]
        }
      ],
      pictures: [
        {
          src: require('@/assets/img/card-5-min.jpg'),
          alt: 'card'
        },
        {
          src: require('@/assets/img/card-6-min.jpg'),
          alt: 'card'
        },
        {
          src: require('@/assets/img/card-7-min.jpg'),
          alt: 'card'
        },
        {
          src: require('@/assets/img/card-8-min.jpg'),
          alt: 'card'
        }
      ]
    }
  }
}
</script>

<style></style>
